return {}
-- return {
--   "pmizio/typescript-tools.nvim",
--   dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
--   opts = {
--     tsserver_file_preferences = function(ft)
--       -- Some "ifology" using `ft` of opened file
--       return {
--         includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all'
--         includeInlayParameterNameHintsWhenArgumentMatchesName = true,
--         includeInlayVariableTypeHints = true,
--         includeInlayFunctionParameterTypeHints = true,
--         includeInlayVariableTypeHintsWhenTypeMatchesName = true,
--         includeInlayPropertyDeclarationTypeHints = true,
--         includeInlayFunctionLikeReturnTypeHints = true,
--         includeInlayEnumMemberValueHints = true,
--         inlay_hints = {
--           enabled = true,
--         },
--       }
--     end,
--     settings = {
--       code_lens = "off",
--       -- inlay_hints = {
--       --   enabled = true,
--       -- },
--     },
--   },
-- }
